name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: splunk-version
    attributes:
      label: Splunk Version
      description: What version of Splunk are you using?
      placeholder: Splunk Enterprise 8.2.1
    validations:
      required: true

  - type: input
    id: addon-version
    attributes:
      label: Add-on Version
      description: What version of the Linode Add-on for Splunk are you using?
      placeholder: 0.0.2
    validations:
      required: true

  - type: textarea
    id: related-inputs
    attributes:
      label: Related Inputs/Features
      description: Which inputs/features are affected by this bug?
      placeholder: linode_account_events

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: List any custom configurations and the steps to reproduce this error
    validations:
      required: true
